disallowed-types = [
  { path = "std::fs::DirEntry", allow-invalid = true },
  { path = "std::fs::File", allow-invalid = true },
  { path = "std::fs::OpenOptions", allow-invalid = true },
  { path = "std::fs::ReadDir", allow-invalid = true },
  { path = "tokio::fs::DirBuilder", allow-invalid = true },
  { path = "tokio::fs::DirEntry", allow-invalid = true },
  { path = "tokio::fs::File", allow-invalid = true },
  { path = "tokio::fs::OpenOptions", allow-invalid = true },
  { path = "tokio::fs::ReadDir", allow-invalid = true },
]

disallowed-methods = [
  { path = "dotenvy::dotenv", allow-invalid = true },
  { path = "dotenvy::dotenv_override", allow-invalid = true },
  { path = "dotenvy::from_filename", allow-invalid = true },
  { path = "dotenvy::from_filename_override", allow-invalid = true },
  { path = "dotenvy::from_path", allow-invalid = true },
  { path = "dotenvy::from_path_override", allow-invalid = true },
  { path = "dotenvy::from_read", allow-invalid = true },
  { path = "dotenvy::from_read_override", allow-invalid = true },
  { path = "dotenvy::var", allow-invalid = true },
  { path = "dotenvy::vars", allow-invalid = true },
  { path = "dotenvy::Iter::load", allow-invalid = true },
  { path = "dotenvy::Iter::load_override", allow-invalid = true },
  { path = "std::fs::canonicalize", allow-invalid = true },
  { path = "std::fs::copy", allow-invalid = true },
  { path = "std::fs::create_dir", allow-invalid = true },
  { path = "std::fs::create_dir_all", allow-invalid = true },
  { path = "std::fs::hard_link", allow-invalid = true },
  { path = "std::fs::metadata", allow-invalid = true },
  { path = "std::fs::read", allow-invalid = true },
  { path = "std::fs::read_dir", allow-invalid = true },
  { path = "std::fs::read_link", allow-invalid = true },
  { path = "std::fs::read_to_string", allow-invalid = true },
  { path = "std::fs::remove_dir", allow-invalid = true },
  { path = "std::fs::remove_dir_all", allow-invalid = true },
  { path = "std::fs::remove_file", allow-invalid = true },
  { path = "std::fs::rename", allow-invalid = true },
  { path = "std::fs::set_permissions", allow-invalid = true },
  { path = "std::fs::soft_link", allow-invalid = true },
  { path = "std::fs::symlink_metadata", allow-invalid = true },
  { path = "std::fs::write", allow-invalid = true },
  { path = "tokio::fs::canonicalize", allow-invalid = true },
  { path = "tokio::fs::copy", allow-invalid = true },
  { path = "tokio::fs::create_dir", allow-invalid = true },
  { path = "tokio::fs::create_dir_all", allow-invalid = true },
  { path = "tokio::fs::hard_link", allow-invalid = true },
  { path = "tokio::fs::metadata", allow-invalid = true },
  { path = "tokio::fs::read", allow-invalid = true },
  { path = "tokio::fs::read_dir", allow-invalid = true },
  { path = "tokio::fs::read_link", allow-invalid = true },
  { path = "tokio::fs::read_to_string", allow-invalid = true },
  { path = "tokio::fs::remove_dir", allow-invalid = true },
  { path = "tokio::fs::remove_dir_all", allow-invalid = true },
  { path = "tokio::fs::remove_file", allow-invalid = true },
  { path = "tokio::fs::rename", allow-invalid = true },
  { path = "tokio::fs::set_permissions", allow-invalid = true },
  { path = "tokio::fs::symlink_metadata", allow-invalid = true },
  { path = "tokio::fs::try_exists", allow-invalid = true },
  { path = "tokio::fs::write", allow-invalid = true },
  { path = "std::os::unix::fs::symlink", allow-invalid = true },
  { path = "std::os::windows::fs::symlink_dir", allow-invalid = true },
  { path = "std::os::windows::fs::symlink_file", allow-invalid = true },
  { path = "tokio::fs::symlink", allow-invalid = true },
  { path = "tokio::fs::symlink_dir", allow-invalid = true },
  { path = "tokio::fs::symlink_file", allow-invalid = true },
]
