//! Conversions between our domain/application types and TBP wire types.
//!
//! Free functions, not trait impls. The orphan rule blocks `TryFrom`/`From`
//! impls here because all involved types (`BotMove` from `tet-application`,
//! `TbpMove` from `tbp`) are foreign to `tet-infrastructure`.
//!
//! Naming: `<source>_to_<destination>`. First word = input, last word = output.
//! Reads as "I have X, I want Y, I call `x_to_y`."

use tet_application::ports::bot::{BotMove, BotPieceLocation, BotSpin};
use tet_application::{BotError, PlayerSnapshot};
use tet_domain::{Cell, MinoType, Orientation};

use crate::codec::{
    Error as TbpError, ErrorCause, MaybeUnknown, Move as TbpMove, Orientation as TbpOrientation,
    Piece as TbpPiece, PieceLocation as TbpPieceLocation, Spin as TbpSpin, Start as TbpStart,
};

// ============ Composite: snapshot → Start ============

/// Build a TBP `Start` message from a player snapshot. Always emits
/// `Known` variants — outbound traffic shouldn't carry `Unknown`.
///
/// Rules go in a separate `FrontendMessage::Rules` sent earlier in the
/// handshake — `Start` only carries current state.
#[must_use]
pub fn snapshot_to_start(snap: &PlayerSnapshot) -> TbpStart {
    let board = board_to_tbp_grid(&snap.board);
    let queue = snap
        .queue
        .iter()
        .map(|m| MaybeUnknown::Known(mino_type_to_tbp_piece(*m)))
        .collect();
    let hold = snap
        .hold
        .map(|m| MaybeUnknown::Known(mino_type_to_tbp_piece(m)));
    // combo can be negative (-1 after a broken combo); clamp negatives to 0
    // since TBP uses u32.
    let combo = u32::try_from(snap.combo).unwrap_or(0);
    // TbpStart's `new` takes the 5 required fields; `randomizer` is filled
    // internally (it's an optional field generated by gen_type!).
    TbpStart::new(hold, queue, combo, snap.b2b, board)
}

/// Convert our `Board` (`VecDeque` of `Vec<Cell>`) into the TBP wire shape
/// (`Vec<Vec<Option<char>>>`), bottom-up. Empty cells → `None`, blocks →
/// their letter (`'I'`, `'O'`, etc.), garbage → `'G'`.
fn board_to_tbp_grid(board: &tet_domain::Board) -> Vec<Vec<Option<char>>> {
    board
        .rows()
        .map(|row| {
            row.iter()
                .map(|cell| match cell {
                    Cell::Empty => None,
                    Cell::Block(t) => Some(
                        t.as_str()
                            .chars()
                            .next()
                            .expect("MinoType::as_str is non-empty"),
                    ),
                    Cell::Garbage => Some('G'),
                })
                .collect()
        })
        .collect()
}

// ============ Move conversion ============

/// Outbound: `BotMove` → `TbpMove`. Infallible: we always emit `Known` variants.
#[must_use]
pub fn bot_move_to_tbp(m: BotMove) -> TbpMove {
    // Use `TbpMove::new` (generated by tbp's gen_type!) instead of struct
    // literal + `..Default::default()` because `TbpMove` has all-required
    // fields and therefore doesn't derive `Default`. The `::new` constructor
    // fills the private `rest` field internally.
    TbpMove::new(
        bot_piece_location_to_tbp(m.location),
        MaybeUnknown::Known(bot_spin_to_tbp(m.spin)),
    )
}

/// Inbound: `TbpMove` → `BotMove`. Fallible: TBP may carry `Unknown` variants.
///
/// # Errors
///
/// - `BotError::Protocol`: any nested field (spin, piece kind, orientation, or
///   coordinate) is `Unknown` from a future-spec bot, or the piece location's
///   `x`/`y` fall outside the `i8` range we use for world coordinates.
pub fn tbp_move_to_bot(m: TbpMove) -> Result<BotMove, BotError> {
    let spin = tbp_spin_to_bot(m.spin)?;
    let location = tbp_piece_location_to_bot(m.location)?;
    Ok(BotMove { location, spin })
}

// ============ PieceLocation conversion ============

/// Outbound: `BotPieceLocation` → `TbpPieceLocation`. Converts bbox anchor → TBP center.
#[must_use]
pub fn bot_piece_location_to_tbp(loc: BotPieceLocation) -> TbpPieceLocation {
    // Convert from bbox anchor (where our `Piece.pos` lives) to TBP center
    // (what the wire format expects).
    let center = MinoType::rotation_center_offset(loc.kind, loc.orientation);
    // `center` is Vec2 (i8 fields). Widen both operands to i32 because
    // TBP coordinates are i32. The inbound fn narrows back to i8.
    let center_x = i32::from(loc.x) + i32::from(center.x);
    let center_y = i32::from(loc.y) + i32::from(center.y);
    // Use `TbpPieceLocation::new` (see note in `bot_move_to_tbp` above).
    TbpPieceLocation::new(
        MaybeUnknown::Known(mino_type_to_tbp_piece(loc.kind)),
        MaybeUnknown::Known(orientation_to_tbp_orientation(loc.orientation)),
        center_x,
        center_y,
    )
}

/// Inbound: `TbpPieceLocation` → `BotPieceLocation`. Converts TBP center → bbox anchor.
///
/// # Errors
///
/// - `BotError::Protocol`: the kind or orientation is `Unknown`, or the resulting
///   bbox anchor coordinate is outside the `i8` range we use.
pub fn tbp_piece_location_to_bot(loc: TbpPieceLocation) -> Result<BotPieceLocation, BotError> {
    let kind = tbp_piece_to_mino_type(loc.kind)?;
    let orientation = tbp_orientation_to_orientation(loc.orientation)?;
    let center = MinoType::rotation_center_offset(kind, orientation);
    // `loc.x, loc.y` is TBP center (i32); convert to bbox anchor (i8).
    let bbox_x = loc.x - i32::from(center.x);
    let bbox_y = loc.y - i32::from(center.y);
    Ok(BotPieceLocation {
        kind,
        orientation,
        x: i8::try_from(bbox_x)
            .map_err(|_| BotError::Protocol("coordinate out of range for i8".into()))?,
        y: i8::try_from(bbox_y)
            .map_err(|_| BotError::Protocol("coordinate out of range for i8".into()))?,
    })
}

// ============ Spin conversion ============

/// Outbound: `BotSpin` → `TbpSpin`. Infallible (variants match 1:1).
#[must_use]
pub fn bot_spin_to_tbp(s: BotSpin) -> TbpSpin {
    match s {
        BotSpin::None => TbpSpin::None,
        BotSpin::Mini => TbpSpin::Mini,
        BotSpin::Full => TbpSpin::Full,
    }
}

/// Inbound: `MaybeUnknown<TbpSpin>` → `BotSpin`. Fallible (`Unknown` is desync).
///
/// # Errors
///
/// - `BotError::Protocol`: the wire-format `spin` was `Unknown` (future-spec variant).
///   A `Known` value with an unrecognized variant panics via `unreachable!` (a bug).
pub fn tbp_spin_to_bot(m: MaybeUnknown<TbpSpin>) -> Result<BotSpin, BotError> {
    match m {
        MaybeUnknown::Known(s) => match s {
            TbpSpin::None => Ok(BotSpin::None),
            TbpSpin::Mini => Ok(BotSpin::Mini),
            TbpSpin::Full => Ok(BotSpin::Full),
            // TbpSpin is `#[non_exhaustive]` upstream.
            _ => unreachable!("TBP protocol added a new spin variant"),
        },
        MaybeUnknown::Unknown(_) => Err(BotError::Protocol("unknown spin variant from bot".into())),
    }
}

// ============ MinoType / TbpPiece conversion ============

/// Outbound: `MinoType` → `TbpPiece`. Infallible (variants match 1:1).
#[must_use]
pub fn mino_type_to_tbp_piece(m: MinoType) -> TbpPiece {
    match m {
        MinoType::I => TbpPiece::I,
        MinoType::O => TbpPiece::O,
        MinoType::T => TbpPiece::T,
        MinoType::S => TbpPiece::S,
        MinoType::Z => TbpPiece::Z,
        MinoType::J => TbpPiece::J,
        MinoType::L => TbpPiece::L,
    }
}

/// Inbound: `MaybeUnknown<TbpPiece>` → `MinoType`. Fallible (`Unknown` is desync).
///
/// # Errors
///
/// - `BotError::Protocol`: the wire-format `kind` was `Unknown` (future-spec variant).
///   A `Known` value with an unrecognized variant panics via `unreachable!` (a bug).
pub fn tbp_piece_to_mino_type(m: MaybeUnknown<TbpPiece>) -> Result<MinoType, BotError> {
    match m {
        MaybeUnknown::Known(p) => match p {
            TbpPiece::I => Ok(MinoType::I),
            TbpPiece::O => Ok(MinoType::O),
            TbpPiece::T => Ok(MinoType::T),
            TbpPiece::S => Ok(MinoType::S),
            TbpPiece::Z => Ok(MinoType::Z),
            TbpPiece::J => Ok(MinoType::J),
            TbpPiece::L => Ok(MinoType::L),
            // TbpPiece is `#[non_exhaustive]` upstream.
            _ => unreachable!("TBP protocol added a new piece variant; update mapper.rs"),
        },
        MaybeUnknown::Unknown(_) => {
            Err(BotError::Protocol("unknown piece variant from bot".into()))
        }
    }
}

// ============ Orientation conversion ============

/// Outbound: `Orientation` → `TbpOrientation`. Infallible (variants match 1:1).
#[must_use]
pub fn orientation_to_tbp_orientation(o: Orientation) -> TbpOrientation {
    match o {
        Orientation::North => TbpOrientation::North,
        Orientation::East => TbpOrientation::East,
        Orientation::South => TbpOrientation::South,
        Orientation::West => TbpOrientation::West,
    }
}

/// Inbound: `MaybeUnknown<TbpOrientation>` → `Orientation`. Fallible.
///
/// # Errors
///
/// - `BotError::Protocol`: the wire-format `orientation` was `Unknown` (future-spec
///   variant). A `Known` value with an unrecognized variant panics via
///   `unreachable!` (a bug).
pub fn tbp_orientation_to_orientation(
    m: MaybeUnknown<TbpOrientation>,
) -> Result<Orientation, BotError> {
    match m {
        MaybeUnknown::Known(o) => match o {
            TbpOrientation::North => Ok(Orientation::North),
            TbpOrientation::East => Ok(Orientation::East),
            TbpOrientation::South => Ok(Orientation::South),
            TbpOrientation::West => Ok(Orientation::West),
            // TbpOrientation is `#[non_exhaustive]` upstream.
            _ => unreachable!("TBP protocol added a new orientation variant"),
        },
        MaybeUnknown::Unknown(_) => Err(BotError::Protocol("unknown orientation from bot".into())),
    }
}

// ============ Cell ↔ TBP board cell ============

/// Outbound: `Cell` → TBP cell. `Empty` → JSON null; `Block(t)` → `t.as_str()`;
/// `Garbage` → `"G"`.
#[must_use]
pub fn cell_to_tbp(c: &Cell) -> Option<&'static str> {
    match c {
        Cell::Empty => None,
        Cell::Block(t) => Some(t.as_str()),
        Cell::Garbage => Some("G"),
    }
}

/// Inbound: TBP cell → `Cell`. `None` → `Empty`; `Some('G')` → `Garbage`;
/// `Some(piece_letter)` → `Block(piece)`; anything else → `BotError::Protocol`.
///
/// # Errors
///
/// - `BotError::Protocol`: the char is not a recognized piece letter (`'G'` for
///   garbage is handled separately).
pub fn cell_from_tbp(c: Option<char>) -> Result<Cell, BotError> {
    match c {
        None => Ok(Cell::Empty),
        Some('G') => Ok(Cell::Garbage),
        Some(c) => MinoType::from_char(c)
            .map(Cell::Block)
            .ok_or_else(|| BotError::Protocol(format!("unknown cell char: {c:?}"))),
    }
}

/// Convert a TBP `error` message into our `BotError`.
///
/// TBP has one known reason (`unsupported_rules`). Any other error
/// reason — including `MaybeUnknown::Unknown` from a future-spec bot —
/// is treated as a protocol violation.
#[must_use]
pub fn tbp_error_to_bot(e: &TbpError) -> BotError {
    match e.reason {
        MaybeUnknown::Known(ErrorCause::UnsupportedRules) => {
            BotError::Protocol("bot does not support our rules".into())
        }
        MaybeUnknown::Unknown(_) => BotError::Protocol("unknown error reason from bot".into()),
        MaybeUnknown::Known(_) => BotError::Protocol("unrecognized error reason from bot".into()),
    }
}

#[cfg(test)]
mod test {
    //! Conversion tests. Focus on:
    //! - The bbox-anchor ↔ TBP-center math (the math error hotspot)
    //! - `MaybeUnknown::Unknown` → error paths (protocol violation detection)
    //! - `i32 → u32` clamping (negative combo)
    //! - One round-trip per enum to verify wiring (per "don't test data" principle,
    //!   we don't exhaustively cover every enum variant — the matches are static).

    use super::*;
    use crate::codec::{
        Error as TbpError, ErrorCause, MaybeUnknown, Move as TbpMove,
        Orientation as TbpOrientation, Piece as TbpPiece, PieceLocation as TbpPieceLocation,
        Spin as TbpSpin,
    };
    use rstest::rstest;
    use serde_json::json;
    use tet_application::ports::bot::{BotMove, BotPieceLocation, BotSpin};
    use tet_application::{Phase, Piece, PlayerSnapshot};
    use tet_domain::{Board, Cell, Vec2};

    // ============ Test fixtures ============

    fn t_snap() -> PlayerSnapshot {
        PlayerSnapshot {
            board: Board::new(10, 25),
            queue: vec![MinoType::I, MinoType::O, MinoType::T],
            hold: Some(MinoType::S),
            combo: 0,
            b2b: false,
            current: Piece::spawn(MinoType::T),
            phase: Phase::Playing,
            pending_garbage: vec![],
        }
    }

    fn piece_loc(kind: MinoType, orientation: Orientation, x: i8, y: i8) -> BotPieceLocation {
        BotPieceLocation {
            kind,
            orientation,
            x,
            y,
        }
    }

    fn tbp_loc(kind: TbpPiece, orientation: TbpOrientation, x: i32, y: i32) -> TbpPieceLocation {
        TbpPieceLocation::new(
            MaybeUnknown::Known(kind),
            MaybeUnknown::Known(orientation),
            x,
            y,
        )
    }

    // ============ snapshot_to_start ============

    #[rstest]
    fn snapshot_to_start_clamps_negative_combo_to_zero() {
        let mut snap = t_snap();
        snap.combo = -1;
        let start = snapshot_to_start(&snap);
        assert_eq!(start.combo, 0);
    }

    #[rstest]
    fn snapshot_to_start_preserves_positive_combo() {
        let mut snap = t_snap();
        snap.combo = 7;
        let start = snapshot_to_start(&snap);
        assert_eq!(start.combo, 7);
    }

    #[rstest]
    fn snapshot_to_start_maps_cells_to_optional_chars() {
        let mut snap = t_snap();
        snap.board.set(Vec2::new(0, 0), Cell::Block(MinoType::I));
        snap.board.set(Vec2::new(1, 0), Cell::Garbage);
        // y=24 leaves it empty.
        let start = snapshot_to_start(&snap);
        assert_eq!(start.board[0][0], Some('I'));
        assert_eq!(start.board[0][1], Some('G'));
        assert_eq!(start.board[24][0], None);
    }

    #[rstest]
    fn snapshot_to_start_maps_hold_and_queue() {
        let snap = t_snap();
        let start = snapshot_to_start(&snap);
        assert!(matches!(start.hold, Some(MaybeUnknown::Known(TbpPiece::S))));
        // TbpPiece doesn't derive PartialEq, so convert back through our domain
        // type for the comparison. TbpPiece isn't Copy either, so clone.
        let queue_pieces: Vec<MinoType> = start
            .queue
            .iter()
            .map(|p| match p {
                MaybeUnknown::Known(p) => {
                    tbp_piece_to_mino_type(MaybeUnknown::Known(p.clone())).unwrap()
                }
                MaybeUnknown::Unknown(_) => panic!("queue should be all Known"),
            })
            .collect();
        assert_eq!(queue_pieces, vec![MinoType::I, MinoType::O, MinoType::T]);
    }

    // ============ bot_move_to_tbp / tbp_move_to_bot: bbox ↔ TBP-center math ============

    #[rstest]
    fn bot_move_to_tbp_i_piece_north_shifts_y_by_1() {
        // I-piece North: center offset (0, 1). bbox (4, 19) → center (4, 20).
        let m = BotMove {
            location: piece_loc(MinoType::I, Orientation::North, 4, 19),
            spin: BotSpin::None,
        };
        let t = bot_move_to_tbp(m);
        assert_eq!(t.location.x, 4);
        assert_eq!(t.location.y, 20);
    }

    #[rstest]
    fn bot_move_to_tbp_o_piece_south_shifts_both_axes() {
        // O-piece South: center offset (2, 2). bbox (3, 18) → center (5, 20).
        let m = BotMove {
            location: piece_loc(MinoType::O, Orientation::South, 3, 18),
            spin: BotSpin::None,
        };
        let t = bot_move_to_tbp(m);
        assert_eq!(t.location.x, 5);
        assert_eq!(t.location.y, 20);
    }

    #[rstest]
    fn tbp_move_to_bot_is_inverse_of_outbound_for_i_piece_north() {
        // bbox (4, 19) → center (4, 20) → bbox (4, 19).
        let original = BotMove {
            location: piece_loc(MinoType::I, Orientation::North, 4, 19),
            spin: BotSpin::None,
        };
        let t = bot_move_to_tbp(original);
        let m = tbp_move_to_bot(t).unwrap();
        assert_eq!(m.location.kind, MinoType::I);
        assert_eq!(m.location.orientation, Orientation::North);
        assert_eq!(m.location.x, 4);
        assert_eq!(m.location.y, 19);
    }

    #[rstest]
    fn tbp_move_to_bot_errors_on_coordinates_outside_i8_range() {
        // TBP allows x/y up to i32; we narrow to i8. 200 doesn't fit.
        let t = TbpMove::new(
            tbp_loc(TbpPiece::J, TbpOrientation::North, 200, 20),
            MaybeUnknown::Known(TbpSpin::None),
        );
        assert!(tbp_move_to_bot(t).is_err());
    }

    // ============ MaybeUnknown error paths ============

    #[rstest]
    fn tbp_move_to_bot_errors_on_unknown_spin() {
        let t = TbpMove::new(
            tbp_loc(TbpPiece::J, TbpOrientation::North, 5, 20),
            MaybeUnknown::Unknown(json!("future-spin")),
        );
        assert!(tbp_move_to_bot(t).is_err());
    }

    #[rstest]
    fn tbp_move_to_bot_errors_on_unknown_piece_kind() {
        let t = TbpMove::new(
            TbpPieceLocation::new(
                MaybeUnknown::Unknown(json!("future-piece")),
                MaybeUnknown::Known(TbpOrientation::North),
                5,
                20,
            ),
            MaybeUnknown::Known(TbpSpin::None),
        );
        assert!(tbp_move_to_bot(t).is_err());
    }

    #[rstest]
    fn tbp_piece_to_mino_type_errors_on_unknown() {
        assert!(tbp_piece_to_mino_type(MaybeUnknown::Unknown(json!("X"))).is_err());
    }

    #[rstest]
    fn tbp_spin_to_bot_errors_on_unknown() {
        assert!(tbp_spin_to_bot(MaybeUnknown::Unknown(json!("spinz"))).is_err());
    }

    #[rstest]
    fn tbp_orientation_to_orientation_errors_on_unknown() {
        assert!(tbp_orientation_to_orientation(MaybeUnknown::Unknown(json!("diag"))).is_err());
    }

    // ============ Enum round-trips (wiring verification) ============

    #[rstest]
    fn mino_type_round_trip_all_variants() {
        // Round-tripping all 7 verifies the wiring without asserting on the
        // wire-format strings (don't test data).
        for m in [
            MinoType::I,
            MinoType::O,
            MinoType::T,
            MinoType::S,
            MinoType::Z,
            MinoType::J,
            MinoType::L,
        ] {
            let t = mino_type_to_tbp_piece(m);
            let back = tbp_piece_to_mino_type(MaybeUnknown::Known(t)).unwrap();
            assert_eq!(m, back, "round-trip failed for {m:?}");
        }
    }

    #[rstest]
    fn orientation_round_trip_all_variants() {
        for o in [
            Orientation::North,
            Orientation::East,
            Orientation::South,
            Orientation::West,
        ] {
            let t = orientation_to_tbp_orientation(o);
            let back = tbp_orientation_to_orientation(MaybeUnknown::Known(t)).unwrap();
            assert_eq!(o, back);
        }
    }

    #[rstest]
    fn spin_round_trip_all_variants() {
        for s in [BotSpin::None, BotSpin::Mini, BotSpin::Full] {
            let t = bot_spin_to_tbp(s);
            let back = tbp_spin_to_bot(MaybeUnknown::Known(t)).unwrap();
            assert_eq!(s, back);
        }
    }

    // ============ Cell conversion ============

    #[rstest]
    fn cell_to_tbp_maps_all_three_variants() {
        assert_eq!(cell_to_tbp(&Cell::Empty), None);
        assert_eq!(cell_to_tbp(&Cell::Block(MinoType::T)), Some("T"));
        assert_eq!(cell_to_tbp(&Cell::Garbage), Some("G"));
    }

    #[rstest]
    fn cell_from_tbp_maps_all_three_cases() {
        assert_eq!(cell_from_tbp(None).unwrap(), Cell::Empty);
        assert_eq!(cell_from_tbp(Some('G')).unwrap(), Cell::Garbage);
        assert_eq!(cell_from_tbp(Some('I')).unwrap(), Cell::Block(MinoType::I));
    }

    #[rstest]
    fn cell_from_tbp_errors_on_unknown_char() {
        // 'X' is not a piece letter (JLSZTIO) nor 'G'.
        let err = cell_from_tbp(Some('X')).unwrap_err();
        assert!(matches!(err, BotError::Protocol(_)));
    }

    // ============ Error mapping ============

    #[rstest]
    fn tbp_error_to_bot_maps_unsupported_rules_to_protocol() {
        let e = TbpError::new(MaybeUnknown::Known(ErrorCause::UnsupportedRules));
        assert!(matches!(tbp_error_to_bot(&e), BotError::Protocol(_)));
    }

    #[rstest]
    fn tbp_error_to_bot_maps_unknown_reason_to_protocol() {
        let e = TbpError::new(MaybeUnknown::Unknown(json!("future-reason")));
        assert!(matches!(tbp_error_to_bot(&e), BotError::Protocol(_)));
    }
}
