name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check:
    name: Lint & test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup - Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          components: clippy, rustfmt
      - name: Format check
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --workspace
      - name: Test
        run: cargo test --workspace
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup - Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@7572810d7dd469b651bb7793945692cf78da5dd7 # v2.85.0
        with:
          tool: cargo-llvm-cov
      - name: Coverage
        run: |
          mkdir -p coverage
          cargo llvm-cov --workspace --lcov --output-path coverage/lcov.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: cargo
          fail_ci_if_error: false
          slug: mammothb/tet-rs
